version: '2'
services:
  app:
    build: .
    command: make development
    volumes:
      - ./:/src
    depends_on:
      - mongo
      - redis
    ports:
      - 9292:9292
    env_file:
      - .env
    networks:
      - default
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=http://localhost:9292/api-docs.json
    ports:
      - 9293:8080
    networks:
      - default
  redis:
    image: redis
    networks:
      - default
  mongo:
    image: mongo:3.0.4
    command: --smallfiles
    volumes:
      - ./data/db:/data/db:rw
      - ./data/dumps:/data/dumps:rw
    networks:
      - default
