development:
  clients:
    default:
      database: <%= ENV['MONGO_DATABASE_DEVELOPMENT'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>
test:
  clients:
    default:
      database: <%= ENV['MONGO_DATABASE_TEST'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>:<%= ENV['MONGO_PORT'] %>